mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
ipv6: false
external-ui: ./yacd
external-controller: 127.0.0.1:9090
secret: ""
hosts: null
profile:
  # open tracing exporter API
  tracing: true
dns:
  enable: true
  use-hosts: true
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
# tun:
#   enable: true
#   stack: gvisor
#   dns-hijack:
#     - 198.18.0.2:53
#   auto-route: true
#   auto-detect-interface: true
proxies:
  - name: hysteria
    type: hysteria
    server: SERVERIP
    port: PORT
    obfs: "OBFS"
    auth_str: PASSWORD
    alpn: "ayaya"
    up: '50'          #若不写单位，默认为Mbps
    down: '50'
    skip-cert-verify: false 
    # retry: 3, // 启动时连接服务器的重试次数。默认为 0 不重试，负数为无限重试
    # retry_interval: 5, // 重试间隔，单位为秒
  - name: HK Azure
    type: trojan
    server: SERVERIP
    port: PORT
    password: PASSWORD
    udp: false
  - name: HK 香港
    type: trojan
    server: SERVERIP
    port: PORT
    password: PASSWORD
    udp: false
proxy-groups:
  - name: PROXY
    proxies:
      - hysteria
      - HK 香港
      - HK Azure
    type: select
  - name: DisneyPlus
    proxies:
      - HK 香港
      - hysteria
      - HK Azure
    type: select
  - name: AUTO
    type: url-test
    proxies:
      - HK 香港
      - hysteria
      - HK Azure
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: Streaming
    proxies:
      - HK 香港
      - HK Azure
      - hysteria
      - DIRECT
    type: select
rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    interval: 86400
  DisneyPlus:
    type: http
    behavior: classical
    path: ./RuleSet/DisneyPlus.yaml
    interval: 86400
  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    interval: 86400
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    interval: 86400
rules:
  - DOMAIN-SUFFIX,acme.sh,DIRECT
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - IP-CIDR,101.32.104.4/32,DIRECT
  - IP-CIDR,101.32.104.41/32,DIRECT
  - IP-CIDR,101.32.104.56/32,DIRECT
  - IP-CIDR,101.32.118.25/32,DIRECT
  - IP-CIDR,101.32.133.16/32,DIRECT
  - IP-CIDR,101.32.133.53/32,DIRECT
  - IP-CIDR,101.32.133.209/32,DIRECT
  - IP-CIDR,129.226.3.47/32,DIRECT
  - IP-CIDR,129.226.107.244/32,DIRECT
  - DOMAIN-SUFFIX,weibo.com,PROXY
  - DOMAIN-SUFFIX,weibo.cn,PROXY
  - DOMAIN-SUFFIX,eggjs.org,PROXY
  - DOMAIN-SUFFIX,imdb.com,PROXY
  - DOMAIN-SUFFIX,xirikm.net,PROXY
  - DOMAIN-SUFFIX,byrut.org,PROXY
  - DOMAIN-SUFFIX,xboxdesignlab.xbox.com,PROXY
  - DOMAIN-SUFFIX,principlerepo.com,PROXY
  - DOMAIN-SUFFIX,forthebadge.com,PROXY
  - DOMAIN-SUFFIX,btc.com,PROXY
  - DOMAIN-SUFFIX,7-zip.org,PROXY
  - DOMAIN-SUFFIX,typora.io,PROXY
  - DOMAIN-SUFFIX,steampowered.com,PROXY
  - DOMAIN-SUFFIX,sourceforge.net,PROXY
  - DOMAIN-SUFFIX,xiaomi.eu,PROXY
  - DOMAIN-SUFFIX,designsystemsforfigma.com,PROXY
  - DOMAIN-SUFFIX,pt1lib.org,PROXY
  - DOMAIN-SUFFIX,feishu.cn,PROXY
  - DOMAIN-SUFFIX,z-lib.org,PROXY
  - DOMAIN-SUFFIX,wireguard.com,PROXY
  - DOMAIN-SUFFIX,flaticon.com,PROXY
  - DOMAIN-SUFFIX,rabbitmq.com,PROXY
  - DOMAIN-SUFFIX,opensea.io,PROXY
  - DOMAIN-SUFFIX,rxliuli.com,PROXY 
  - DOMAIN-SUFFIX,mrsheep.xyz,PROXY 
  - DOMAIN-SUFFIX,g.co,PROXY
  - DOMAIN-SUFFIX,browzzy.com,PROXY
  - DOMAIN-SUFFIX,wakatime.com,PROXY
  - DOMAIN-SUFFIX,hostloc.com,PROXY
  - DOMAIN-SUFFIX,cloudflare.com,PROXY
  - DOMAIN-SUFFIX,ift.tt,PROXY
  - DOMAIN-SUFFIX,youtrack.jetbrains.com,PROXY
  - DOMAIN-KEYWORD,mvnrepository,PROXY
  - DOMAIN-SUFFIX,okx.com,PROXY
  - DOMAIN,nextjs.org,PROXY
  - DOMAIN,v2rayssr.com,PROXY
  - DOMAIN,yugogo.xyz,PROXY
  - DOMAIN,monkeytype.com,PROXY
  - DOMAIN,cn1lib.org,PROXY
  - DOMAIN,cn1lib.org,PROXY
  - DOMAIN,kuaichedao.co,PROXY
  - DOMAIN,bgp.he.net,PROXY
  - DOMAIN-SUFFIX,github.blog,PROXY
  - DOMAIN,luciovilla.com,PROXY
  - DOMAIN,www.heibaizhibo.com,PROXY
  - DOMAIN,emojiall.com,PROXY
  - DOMAIN,www.msftconnecttest.com,PROXY
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,DisneyPlus,DisneyPlus
  - RULE-SET,Streaming,Streaming
  - RULE-SET,Global,PROXY
  - RULE-SET,China,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY