mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
ipv6: false
external-ui: ./yacd
external-controller: 127.0.0.1:9090
secret: ""
hosts: null
profile:
  # open tracing exporter API
  tracing: true
dns:
  enable: true
  use-hosts: true
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
# tun:
#   enable: true
#   stack: gvisor
#   dns-hijack:
#     - 198.18.0.2:53
#   auto-route: true
#   auto-detect-interface: true
proxies:
  - name: hysteria
    type: hysteria
    server: SERVERIP
    port: PORT
    obfs: "OBFS"
    auth_str: PASSWORD
    alpn: "ayaya"
    up: '50'          #若不写单位，默认为Mbps
    down: '50'
    skip-cert-verify: false 
    # retry: 3, // 启动时连接服务器的重试次数。默认为 0 不重试，负数为无限重试
    # retry_interval: 5, // 重试间隔，单位为秒
  - name: HK Azure
    type: trojan
    server: SERVERIP
    port: PORT
    password: PASSWORD
    udp: false
  - name: HK 香港
    type: trojan
    server: SERVERIP
    port: PORT
    password: PASSWORD
    udp: false
proxy-groups:
  - name: PROXY
    proxies:
      - hysteria
      - HK 香港
      - HK Azure
    type: select
  - name: AUTO
    type: url-test
    proxies:
      - HK 香港
      - hysteria
      - HK Azure
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: Streaming
    proxies:
      - HK 香港
      - HK Azure
      - hysteria
      - DIRECT
    type: select
rule-providers:
  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/Streaming.yaml
    url: "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml"
    interval: 86400
rules:
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,facebook,PROXY
  - GEOSITE,youtube,PROXY
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,cn,DIRECT
  - RULE-SET,Streaming,Streaming
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY